/**
 * PresetBank - Manages preset/patch storage and recall for FirstSynth
 * 32 presets inspired by classic synthesizers
 */

export class PresetBank {
    constructor() {
        this.presets = new Map();
        this.currentPresetIndex = 0;
        this.initializeDefaultPresets();
    }

    initializeDefaultPresets() {

        // 1. Init
        this.presets.set(0, {
            name: "Init",
            index: 0,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":10},{"name":"env1Decay","value":100},{"name":"env1Release","value":300},{"name":"env1Sustain","value":70},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":2000},{"name":"filterResonance","value":50},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":80},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":50},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 2. Bright Lead
        this.presets.set(1, {
            name: "Bright Lead",
            index: 1,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":5},{"name":"env1Decay","value":150},{"name":"env1Release","value":200},{"name":"env1Sustain","value":80},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":4500},{"name":"filterResonance","value":400},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":8},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":50},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":80},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":30},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 3. Warm Pad
        this.presets.set(2, {
            name: "Warm Pad",
            index: 2,
            parameters: [{"name":"chorusAmount","value":30},{"name":"env1Attack","value":500},{"name":"env1Decay","value":1000},{"name":"env1Release","value":1500},{"name":"env1Sustain","value":75},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3000},{"name":"filterResonance","value":200},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":90},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":40},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":85},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":7},{"name":"osc2WaveshapeIn","value":35},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":60},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":25},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":80}]
        });

        // 4. Deep Bass
        this.presets.set(3, {
            name: "Deep Bass",
            index: 3,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":20},{"name":"env1Decay","value":200},{"name":"env1Release","value":400},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":800},{"name":"filterResonance","value":150},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":110},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":-12},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":-24},{"name":"osc2WaveshapeIn","value":15},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 5. Bright Bell
        this.presets.set(4, {
            name: "Bright Bell",
            index: 4,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":1500},{"name":"env1Release","value":2000},{"name":"env1Sustain","value":0},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":5000},{"name":"filterResonance","value":500},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":30},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":3},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":90},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":19},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":70},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":28},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 6. Dark Strings
        this.presets.set(5, {
            name: "Dark Strings",
            index: 5,
            parameters: [{"name":"chorusAmount","value":40},{"name":"env1Attack","value":800},{"name":"env1Decay","value":500},{"name":"env1Release","value":1200},{"name":"env1Sustain","value":85},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":2000},{"name":"filterResonance","value":300},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":95},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":60},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":90},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":-12},{"name":"osc2WaveshapeIn","value":55},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":50},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":50},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":90}]
        });

        // 7. Acid
        this.presets.set(6, {
            name: "Acid",
            index: 6,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":2},{"name":"env1Decay","value":100},{"name":"env1Release","value":50},{"name":"env1Sustain","value":0},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":8000},{"name":"filterResonance","value":800},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":200},{"name":"lfo1WaveShape","value":3},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":-5},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":99},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":0},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":0},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 8. Soft Lead
        this.presets.set(7, {
            name: "Soft Lead",
            index: 7,
            parameters: [{"name":"chorusAmount","value":20},{"name":"env1Attack","value":100},{"name":"env1Decay","value":200},{"name":"env1Release","value":250},{"name":"env1Sustain","value":80},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3500},{"name":"filterResonance","value":350},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":110},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":25},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":70},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":5},{"name":"osc2WaveshapeIn","value":20},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":40}]
        });

        // 9. Screaming Lead
        this.presets.set(8, {
            name: "Screaming Lead",
            index: 8,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":80},{"name":"env1Release","value":150},{"name":"env1Sustain","value":90},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":6000},{"name":"filterResonance","value":600},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":50},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":75},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":40},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":80},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 10. Classic Brass
        this.presets.set(9, {
            name: "Classic Brass",
            index: 9,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":50},{"name":"env1Decay","value":300},{"name":"env1Release","value":400},{"name":"env1Sustain","value":80},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":4000},{"name":"filterResonance","value":400},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":110},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":45},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":50},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":70},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":19},{"name":"osc3WaveshapeIn","value":40},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 11. French Horn
        this.presets.set(10, {
            name: "French Horn",
            index: 10,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":150},{"name":"env1Decay","value":400},{"name":"env1Release","value":500},{"name":"env1Sustain","value":75},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3000},{"name":"filterResonance","value":300},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":-12},{"name":"osc1WaveshapeIn","value":30},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":95},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":35},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":60},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":7},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":60}]
        });

        // 12. Synth Strings
        this.presets.set(11, {
            name: "Synth Strings",
            index: 11,
            parameters: [{"name":"chorusAmount","value":50},{"name":"env1Attack","value":600},{"name":"env1Decay","value":800},{"name":"env1Release","value":1000},{"name":"env1Sustain","value":80},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":2500},{"name":"filterResonance","value":250},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":85},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":-12},{"name":"osc1WaveshapeIn","value":50},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":90},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":45},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":70},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":12},{"name":"osc3WaveshapeIn","value":40},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":100}]
        });

        // 13. Pluck
        this.presets.set(12, {
            name: "Pluck",
            index: 12,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":150},{"name":"env1Release","value":100},{"name":"env1Sustain","value":0},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3500},{"name":"filterResonance","value":400},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":110},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":20},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":80},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":25},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 14. AM Bells
        this.presets.set(13, {
            name: "AM Bells",
            index: 13,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":1200},{"name":"env1Release","value":1500},{"name":"env1Sustain","value":0},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":5500},{"name":"filterResonance","value":450},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":19},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":80},{"name":"stereoSpread","value":30}]
        });

        // 15. Wobble Bass
        this.presets.set(14, {
            name: "Wobble Bass",
            index: 14,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":10},{"name":"env1Decay","value":100},{"name":"env1Release","value":200},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":1200},{"name":"filterResonance","value":250},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":80},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":110},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":4},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":-12},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":-24},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 16. Sub Bass
        this.presets.set(15, {
            name: "Sub Bass",
            index: 15,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":15},{"name":"env1Decay","value":150},{"name":"env1Release","value":300},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":500},{"name":"filterResonance","value":100},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":120},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":-24},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":0},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":0},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 17. Glass Harmonica
        this.presets.set(16, {
            name: "Glass Harmonica",
            index: 16,
            parameters: [{"name":"chorusAmount","value":60},{"name":"env1Attack","value":200},{"name":"env1Decay","value":500},{"name":"env1Release","value":1000},{"name":"env1Sustain","value":70},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":4000},{"name":"filterResonance","value":600},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":40},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":80},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":80},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":50},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":19},{"name":"osc2WaveshapeIn","value":75},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":70}]
        });

        // 18. Choir
        this.presets.set(17, {
            name: "Choir",
            index: 17,
            parameters: [{"name":"chorusAmount","value":80},{"name":"env1Attack","value":400},{"name":"env1Decay","value":600},{"name":"env1Release","value":1200},{"name":"env1Sustain","value":85},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":2500},{"name":"filterResonance","value":50},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":90},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":70},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":85},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":-12},{"name":"osc2WaveshapeIn","value":65},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":75},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":12},{"name":"osc3WaveshapeIn","value":60},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":100}]
        });

        // 19. Organ
        this.presets.set(18, {
            name: "Organ",
            index: 18,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":50},{"name":"env1Release","value":100},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":8000},{"name":"filterResonance","value":100},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":99},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":99},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":80},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":19},{"name":"osc3WaveshapeIn","value":99},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 20. Flute
        this.presets.set(19, {
            name: "Flute",
            index: 19,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":100},{"name":"env1Decay","value":200},{"name":"env1Release","value":300},{"name":"env1Sustain","value":80},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":5000},{"name":"filterResonance","value":100},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":20},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":0},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":0},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 21. Harmonic
        this.presets.set(20, {
            name: "Harmonic",
            index: 20,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":10},{"name":"env1Decay","value":100},{"name":"env1Release","value":200},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3500},{"name":"filterResonance","value":400},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":100},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":19},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":50},{"name":"stereoSpread","value":30}]
        });

        // 22. Vowel
        this.presets.set(21, {
            name: "Vowel",
            index: 21,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":300},{"name":"env1Decay","value":400},{"name":"env1Release","value":500},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":2000},{"name":"filterResonance","value":300},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":110},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":80},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":-12},{"name":"osc2WaveshapeIn","value":70},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":90},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":19},{"name":"osc3WaveshapeIn","value":75},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 23. Phase Lead
        this.presets.set(22, {
            name: "Phase Lead",
            index: 22,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":5},{"name":"env1Decay","value":100},{"name":"env1Release","value":150},{"name":"env1Sustain","value":90},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":4000},{"name":"filterResonance","value":500},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":100},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":5},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":50},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":50},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 24. Ring Mod Bell
        this.presets.set(23, {
            name: "Ring Mod Bell",
            index: 23,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":1500},{"name":"env1Release","value":2000},{"name":"env1Sustain","value":0},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":6000},{"name":"filterResonance","value":500},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":19},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":100},{"name":"stereoSpread","value":30}]
        });

        // 25. Noise Filtered
        this.presets.set(24, {
            name: "Noise Filtered",
            index: 24,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":50},{"name":"env1Decay","value":200},{"name":"env1Release","value":300},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3000},{"name":"filterResonance","value":200},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":80},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":50},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":100},{"name":"osc3NoiseAmount","value":100},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 26. Swept Filter
        this.presets.set(25, {
            name: "Swept Filter",
            index: 25,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":10},{"name":"env1Decay","value":100},{"name":"env1Release","value":300},{"name":"env1Sustain","value":70},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":5000},{"name":"filterResonance","value":400},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":150},{"name":"lfo1WaveShape","value":1},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":8},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 27. Electric Piano
        this.presets.set(26, {
            name: "Electric Piano",
            index: 26,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":200},{"name":"env1Release","value":150},{"name":"env1Sustain","value":0},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":4500},{"name":"filterResonance","value":200},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":-12},{"name":"osc1WaveshapeIn","value":40},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":35},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 28. Glassy Shimmer
        this.presets.set(27, {
            name: "Glassy Shimmer",
            index: 27,
            parameters: [{"name":"chorusAmount","value":70},{"name":"env1Attack","value":500},{"name":"env1Decay","value":1000},{"name":"env1Release","value":1500},{"name":"env1Sustain","value":80},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":5500},{"name":"filterResonance","value":50},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":80},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":50},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":19},{"name":"osc2WaveshapeIn","value":40},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":90},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":28},{"name":"osc3WaveshapeIn","value":45},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":100}]
        });

        // 29. Dark Resonance
        this.presets.set(28, {
            name: "Dark Resonance",
            index: 28,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":100},{"name":"env1Decay","value":200},{"name":"env1Release","value":300},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":1800},{"name":"filterResonance","value":850},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":60},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":6},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":100},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":75},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":90},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":70},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 30. Arpeggiator
        this.presets.set(29, {
            name: "Arpeggiator",
            index: 29,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":5},{"name":"env1Decay","value":80},{"name":"env1Release","value":200},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":4000},{"name":"filterResonance","value":500},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":180},{"name":"lfo1WaveShape","value":2},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":30},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":25},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 31. Metallic Sync
        this.presets.set(30, {
            name: "Metallic Sync",
            index: 30,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":1},{"name":"env1Decay","value":150},{"name":"env1Release","value":200},{"name":"env1Sustain","value":75},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":5000},{"name":"filterResonance","value":600},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":1},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":110},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":15},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":100},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":1},{"name":"osc2Transpose","value":12},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

        // 32. Moog-like
        this.presets.set(31, {
            name: "Moog-like",
            index: 31,
            parameters: [{"name":"chorusAmount","value":0},{"name":"env1Attack","value":10},{"name":"env1Decay","value":150},{"name":"env1Release","value":300},{"name":"env1Sustain","value":100},{"name":"env2Attack","value":10},{"name":"env2Decay","value":100},{"name":"env2Release","value":300},{"name":"env2Sustain","value":100},{"name":"env3Attack","value":10},{"name":"env3Decay","value":100},{"name":"env3Release","value":300},{"name":"env3Sustain","value":100},{"name":"filterCutoff","value":3000},{"name":"filterResonance","value":900},{"name":"filterType","value":0},{"name":"lfo1Ramp","value":0},{"name":"lfo1Rate","value":50},{"name":"lfo1WaveShape","value":0},{"name":"lfo2Ramp","value":0},{"name":"lfo2Rate","value":50},{"name":"lfo2WaveShape","value":0},{"name":"lfo3Ramp","value":0},{"name":"lfo3Rate","value":50},{"name":"lfo3WaveShape","value":0},{"name":"mainGain","value":100},{"name":"mtxRow1Dest1","value":0},{"name":"mtxRow1Dest2","value":0},{"name":"mtxRow1Multiplier","value":-8},{"name":"mtxRow1Source","value":0},{"name":"mtxRow2Dest1","value":0},{"name":"mtxRow2Dest2","value":0},{"name":"mtxRow2Multiplier","value":1},{"name":"mtxRow2Source","value":1},{"name":"mtxRow3Dest1","value":0},{"name":"mtxRow3Dest2","value":0},{"name":"mtxRow3Multiplier","value":1},{"name":"mtxRow3Source","value":2},{"name":"mtxRow4Dest1","value":0},{"name":"mtxRow4Dest2","value":0},{"name":"mtxRow4Multiplier","value":1},{"name":"mtxRow4Source","value":3},{"name":"mtxRow5Dest1","value":0},{"name":"mtxRow5Dest2","value":0},{"name":"mtxRow5Multiplier","value":1},{"name":"mtxRow5Source","value":4},{"name":"mtxRow6Dest1","value":0},{"name":"mtxRow6Dest2","value":0},{"name":"mtxRow6Multiplier","value":1},{"name":"mtxRow6Source","value":5},{"name":"mtxRow7Dest1","value":0},{"name":"mtxRow7Dest2","value":0},{"name":"mtxRow7Multiplier","value":1},{"name":"mtxRow7Source","value":6},{"name":"mtxRow8Dest1","value":0},{"name":"mtxRow8Dest2","value":0},{"name":"mtxRow8Multiplier","value":1},{"name":"mtxRow8Source","value":7},{"name":"osc1Detune","value":0},{"name":"osc1Gain","value":120},{"name":"osc1Pan","value":0},{"name":"osc1Saturation","value":0},{"name":"osc1SaturationType","value":0},{"name":"osc1Transpose","value":0},{"name":"osc1WaveshapeIn","value":99},{"name":"osc2Detune","value":5},{"name":"osc2Gain","value":50},{"name":"osc2Pan","value":0},{"name":"osc2Saturation","value":0},{"name":"osc2SaturationType","value":0},{"name":"osc2Sync","value":0},{"name":"osc2Transpose","value":0},{"name":"osc2WaveshapeIn","value":0},{"name":"osc3Detune","value":0},{"name":"osc3Gain","value":30},{"name":"osc3NoiseAmount","value":0},{"name":"osc3NoiseType","value":0},{"name":"osc3Pan","value":0},{"name":"osc3Saturation","value":0},{"name":"osc3SaturationType","value":0},{"name":"osc3Transpose","value":0},{"name":"osc3WaveshapeIn","value":0},{"name":"rmAmount","value":0},{"name":"stereoSpread","value":30}]
        });

    }

    // Get a preset by index
    getPreset(index) {
        return this.presets.get(index);
    }

    // Get list of all presets
    getPresetList() {
        const list = [];
        for (const [index, preset] of this.presets) {
            list.push({ index, name: preset.name });
        }
        return list.sort((a, b) => a.index - b.index);
    }

    // Send preset parameters to the patch connection
    async sendParametersToPatchConnection(patchConnection, presetIndex) {
        const preset = this.getPreset(presetIndex);
        if (!preset || !patchConnection) return;

        // Send all parameters from the preset
        for (const { name, value } of preset.parameters) {
            patchConnection.sendEventOrValue(name, value);
        }
    }

    // Allow preset parameters to be set directly
    setPresetParameters(presetIndex, parametersArray) {
        const preset = this.presets.get(presetIndex);
        if (preset) {
            preset.parameters = parametersArray;
        }
    }
}
